version: '3.4'

services:
  nodepki:
    image: adito/nodepki-docker:production
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
      API_USERNAME: ${API_USERNAME}
      API_PASSWORD: ${API_PASSWORD}
      CA_API_SERVER_BIND_IP_ADDRESS: ${CA_API_SERVER_BIND_IP_ADDRESS}
      CA_API_SERVER_URL: ${CA_API_SERVER_URL}
      CA_API_SERVER_PLAIN_PORT: ${CA_API_SERVER_PLAIN_PORT}
      CA_API_SERVER_TLS_PORT: ${CA_API_SERVER_TLS_PORT}
      CA_API_SERVER_TLS_ENABLED: ${CA_API_SERVER_TLS_ENABLED}
      CA_WEBCLIENT_SERVER_URL: ${CA_WEBCLIENT_SERVER_URL}
      CA_WEBCLIENT_BIND_IP_ADDRESS: ${CA_WEBCLIENT_BIND_IP_ADDRESS}
      CA_WEBCLIENT_SERVER_PORT: ${CA_WEBCLIENT_SERVER_PORT}
      CA_OSCP_SERVER_URL: ${CA_OSCP_SERVER_URL}
      CA_OSCP_SERVER_PORT: ${CA_OSCP_SERVER_PORT}
      CA_WEBCLIENT_HTTP_URL: ${CA_WEBCLIENT_HTTP_URL}
      CA_CRL_SERVER_HTTP_URL: ${CA_CRL_SERVER_HTTP_URL}
      CA_OSCP_SERVER_HTTP_URL: ${CA_OSCP_SERVER_HTTP_URL}
      COUNTRY_CODE: ${COUNTRY_CODE}
      STATE_NAME: ${STATE_NAME}
      LOCALITY_NAME: ${LOCALITY_NAME}
      ORGANIZATION_NAME: ${ORGANIZATION_NAME}
      CERT_MIN_LIFETIME_IN_DAYS: ${CERT_MIN_LIFETIME_IN_DAYS}
      CERT_MAX_LIFETIME_IN_DAYS: ${CERT_MAX_LIFETIME_IN_DAYS}
      ROOT_PASSPHRASE: ${ROOT_PASSPHRASE}
      INTERMEDIATE_PASSPHRASE: ${INTERMEDIATE_PASSPHRASE}
      OCSP_PASSPHRASE: ${OCSP_PASSPHRASE}
      CA_CERT_EXPIRE_IN_DAYS: ${CA_CERT_EXPIRE_IN_DAYS}
      ROOT_CA_COMMON_NAME: ${ROOT_CA_COMMON_NAME}
      INTERMEDIATE_CA_COMMON_NAME: ${INTERMEDIATE_CA_COMMON_NAME}
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:$${CA_WEBCLIENT_SERVER_PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /opt/data/nodepki:/opt/nodepki/data
      - /opt/data/nodepki-client:/opt/nodepki-client/data
      - /opt/data/nodepki-webclient:/opt/nodepki-webclient/data
      - /opt/data/nodepki-certs:/opt/nodepki-client/out
    extra_hosts:
      - ${CA_API_SERVER_URL}:127.0.0.1
    labels:
      traefik.ca-admin.port: ${CA_WEBCLIENT_SERVER_PORT}
      traefik.ca-admin.frontend.rule: Host:${CA_WEBCLIENT_SERVER_URL}
      traefik.ca-admin.protocol: http
      traefik.ca.port: ${CA_API_SERVER_PLAIN_PORT}
      traefik.ca.frontend.rule: Host:${CA_API_SERVER_URL}
      traefik.ca.protocol: http
      traefik.ocsp.port: ${CA_OSCP_SERVER_PORT}
      traefik.ocsp.frontend.rule: Host:${CA_OSCP_SERVER_URL}
      traefik.ocsp.protocol: http
    ports:
      - 5000:5000
      - 2560:2560
      - 8080:8080
